/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author damien
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(serviceWebREST.DetecteurIntrusionFacadeREST.class);
        resources.add(serviceWebREST.AttributionSecteurCameraFacadeREST.class);
        resources.add(serviceWebREST.AttributionSecteurBorneAccesFacadeREST.class);
        resources.add(serviceWebREST.PositionFacadeREST.class);
        resources.add(serviceWebREST.BadgeFacadeREST.class);
        resources.add(serviceWebREST.AccesFacadeREST.class);
        resources.add(serviceWebREST.TechnicienFacadeREST.class);
        resources.add(serviceWebREST.AdministrateurFacadeREST.class);
        resources.add(serviceWebREST.NumeroPredefinisFacadeREST.class);
        resources.add(serviceWebREST.AttributionUtilisateurBadgeFacadeREST.class);
        resources.add(serviceWebREST.PhotoFacadeREST.class);
        resources.add(serviceWebREST.IntrusionFacadeREST.class);
        resources.add(serviceWebREST.CameraFacadeREST.class);
        resources.add(serviceWebREST.AttributionSecteurDetecteurIntrusionFacadeREST.class);
        resources.add(serviceWebREST.AuthorisationAccesFacadeREST.class);
        resources.add(serviceWebREST.UtilisateurFacadeREST.class);
        resources.add(serviceWebREST.EvenementFacadeREST.class);
        resources.add(serviceWebREST.BorneAccesFacadeREST.class);
        resources.add(serviceWebREST.SecteurFacadeREST.class);
        return resources;
    }
    
}
